- .github/CODEOWNERS
- repo.yml
- sensor/scripts/take_measurement.py
Added detection for BME680 sensors on 0x76 and 0x77
> Support secondary i2c address

- sensor/Dockerfile.template
> Fix python version - latest is failing to build

- sensor/scripts/bme680_air_quality.py
- sensor/scripts/take_measurement.py
> Change reading frequency to keep measurements inline with baseline

- grafana/api.sh
> Change grafana endpoint to remove auth requirement

- sensor/scripts/bme680.py
> Resolve issue where accuracy score being stored as float

- sensor/scripts/bme680.py
Reverts balena-io-projects/balena-sense#17
> Revert "Resolve issue where accuracy score being stored as float"

- sensor/Dockerfile.template
> Make sensor entry.sh executable

- telegraf/entry.sh
- telegraf/telegraf.conf
> Added options for external InfluxDB feed

- README.md
> Update README to include new config vars for external DBs

- sensor/Dockerfile.template
> Bump BSEC version to latest

- sensor/Dockerfile.template
- sensor/entry.sh
> Clear previous state data on BSEC library upgrade. Fixes #28

- grafana/provisioning/dashboards/balena-sense.json
> Set mbar units on default dashboard fixes #39

- sensor/scripts/sensor.py
Co-authored-by: Gergely Imreh <gergely@imreh.net>
> Resolve Sense-HAT readings issue fixes #42

- CONTRIBUTING.md
> Correct project name in CONTRIBUTING.md

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
> Update codeowners, add PR template

- grafana/entry.sh
- influxdb/Dockerfile.aarch64
- influxdb/Dockerfile.template
- sensor/Dockerfile.aarch64
- sensor/Dockerfile.template
- sensor/entry.sh
- telegraf/Dockerfile.template
- telegraf/entry.sh
Signed-off-by: Rahul Thakoor <rahul@balena.io>
> Use exec version of CMD and exec in scripts

- influxdb/Dockerfile.aarch64
- influxdb/Dockerfile.template
Connects-to: #53
Signed-off-by: Tomás Migone <tomas@balena.io>
> influxdb: Fix config file path location

- .github/CODEOWNERS
Signed-off-by: Tomás Migone <tomas@balena.io>
> meta: Add @alanb128 to codeowners

- sensor/scripts/sensor.py
> Reinstate BME680 object load

- README.md
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Add a "deploy to balena" button

- sensor/scripts/lps25h.py
- sensor/scripts/sense_hat_air_quality.py
> Add Sense-HAT pressure sensor support

- influxdb/Dockerfile.template
> Pin Alpine version for influxdb

- repo.yml
> Enable balena builds for CI

- README.md
Add masterclass reference to readme. This shouldn't break anything.
Signed-off-by: Andrew Nhem <andrewn@balena.io>
> Including masterclass link to readme

- sensor/Dockerfile.aarch64
- sensor/Dockerfile.template
- sensor/bsec_bme680_linux/LICENSE
- sensor/bsec_bme680_linux/bsec_bme680.c
- sensor/bsec_bme680_linux/make.config
- sensor/bsec_bme680_linux/make.sh
- sensor/bsec_bme680_linux/patches/eCO2+bVOCe.diff
- sensor/scripts/sensor.py
Signed-off-by: Rahul Thakoor <rahul@balena.io>
Depends-on: https://github.com/balena-io-playground/bsec_bme680_linux/pull/1
> Bump BSEC version to 1.4.8

- Dockerfile
- docker-compose.yml
- start.sh
> minor: change hostname via sensor

- balena.yml
Signed-off-by: Alan Boris alan@balena.io
> patch: update logo file

- .gitignore
> Adding Landr-created directories and files to repo

- README.md
Signed-off-by: Alan Boris alan@balena.io
> patch: updated verbiage

- .github/workflows/flowzone.yml
- ARCHITECTURE.md
- Dockerfile
- README.md
- docker-compose.yml
- docs/01-getting-started.md
- docs/03-customization.md
Signed-off-by: Flynn Joffray <flynn@balena.io>
> moving from balenablocks to balena-labs-projects
